Backend56: introduced reviews
The-Chefs/ProiectColectivG4-2021 pull request #152
Opened 2022-01-04 18:12 UTC by Stefpark77

# Justification

#56 
# Implementation

added reviews 

# Testing

[TODO: Detail the testing done to ensure this submission meets requirements. Include automated/manual test additions or modifications.](http://localhost:8080/kitchen/swagger-ui/#/)

# Checklist

- [ ] I tested changes to product code in product
- [ ] I considered updates to the README
- [ ] I considered updates to the error code dictionary

2022-01-04 18:20 UTC, madalinazele approved these changes

2022-01-05 05:41 UTC, EnsyFane commented
We need to be able to get all reviews for a recipe

2022-01-05 16:44 UTC, EnsyFane requested changes
We need a route for getting all reviews for a recipe. Without it the API is not useful

2022-01-07 09:53 UTC, Stefpark77 commented
>

2022-01-07 09:53 UTC, closed without merging