Users/asuciu/recipe details page
The-Chefs/ProiectColectivG4-2021 pull request #81
Opened 2021-11-11 19:52 UTC by suciuandra

# Justification

#46 

# Implementation

Added recipe details page, create recipe button on recipes page and updated scroll style.

2021-11-12 08:14 UTC, EnsyFane approved these changes

2021-11-12 08:14 UTC, EnsyFane commented on iChef-WebUi/src/app/app-routing.module.ts
> +    {path: 'recipes/details', component: RecipeDetailsComponent}
Can we have the id of the recipe in the url? We need this to be able to share links.

2021-11-12 08:14 UTC, EnsyFane commented on iChef-WebUi/src/app/data-types/recipe.ts
> +    id?: number;
id is going to be a string. in the backend we will store it as a GUID

2021-11-12 08:14 UTC, EnsyFane commented on iChef-WebUi/src/app/data-types/recipe.ts
> +    id?: number;
all ids are GUIDs

2021-11-12 08:14 UTC, EnsyFane commented on iChef-WebUi/src/app/styles/mixins.scss
> +    height: 85%;
remove unnecessary white lines

2021-11-12 08:14 UTC, EnsyFane commented
Also, post screenshots of the page

2021-11-13 20:55 UTC, PinkyPotrick requested changes

2021-11-13 20:55 UTC, PinkyPotrick commented on iChef-WebUi/src/app/styles/variables.scss
> +$primary-color2: rgba($color:#E98074, $alpha:0.75);
I don't think that 'primary-color2' is a good name, maybe rename it to 'primary-color-faded' or other specific term. 
Update: You used the term 'transparent' below, that could work as well.

2021-11-13 20:55 UTC, PinkyPotrick approved these changes

2021-11-17 20:31 UTC, mirunatodea approved these changes

2021-11-18 08:05 UTC, merged